Update dependency commander to v14 (#6439)
This PR contains the following updates:

| Package | Change | [Age](https://docs.renovatebot.com/merge-confidence/) | [Confidence](https://docs.renovatebot.com/merge-confidence/) |
|---|---|---|---|
| [commander](https://redirect.github.com/tj/commander.js) | [`12.1.0` → `14.0.3`](https://renovatebot.com/diffs/npm/commander/12.0.0/14.0.3) | ![age](https://developer.mend.io/api/mc/badges/age/npm/commander/14.0.3?slim=true) | ![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/commander/12.0.0/14.0.3?slim=true) |

---

### Release Notes

<details>
<summary>tj/commander.js (commander)</summary>

### [`v14.0.3`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1403-2026-01-31)

[Compare Source](https://redirect.github.com/tj/commander.js/compare/v14.0.2...v14.0.3)

##### Added

- Release Policy document (\[[#&#8203;2462](https://redirect.github.com/tj/commander.js/issues/2462)])

##### Changes

- old major versions now supported for 12 months instead of just previous major version, to give predictable end-of-life date (\[[#&#8203;2462](https://redirect.github.com/tj/commander.js/issues/2462)])
- clarify typing for deprecated callback parameter to `.outputHelp()` (\[[#&#8203;2427](https://redirect.github.com/tj/commander.js/issues/2427)])
- simple readability improvements to README (\[[#&#8203;2465](https://redirect.github.com/tj/commander.js/issues/2465)])

### [`v14.0.2`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1402-2025-10-25)

[Compare Source](https://redirect.github.com/tj/commander.js/compare/v14.0.1...v14.0.2)

##### Changed

- improve negative number auto-detection test (\[[#&#8203;2428](https://redirect.github.com/tj/commander.js/issues/2428)])
- update (dev) dependencies

### [`v14.0.1`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1401-2025-09-12)

[Compare Source](https://redirect.github.com/tj/commander.js/compare/v14.0.0...v14.0.1)

##### Fixed

- broken markdown link in README (\[[#&#8203;2369](https://redirect.github.com/tj/commander.js/issues/2369)])

##### Changed

- improve code readability by using optional chaining (\[[#&#8203;2394](https://redirect.github.com/tj/commander.js/issues/2394)])
- use more idiomatic code with object spread instead of `Object.assign()` (\[[#&#8203;2395](https://redirect.github.com/tj/commander.js/issues/2395)])
- improve code readability using `string.endsWith()` instead of `string.slice()` (\[[#&#8203;2396](https://redirect.github.com/tj/commander.js/issues/2396)])
- refactor `.parseOptions()` to process args array in-place (\[[#&#8203;2409](https://redirect.github.com/tj/commander.js/issues/2409)])
- change private variadic support routines from `._concatValue()` to `._collectValue()` (change code from `array.concat()` to `array.push()`) (\[[#&#8203;2410](https://redirect.github.com/tj/commander.js/issues/2410)])
- update (dev) dependencies

### [`v14.0.0`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1400-2025-05-18)

[Compare Source](https://redirect.github.com/tj/commander.js/compare/v13.1.0...v14.0.0)

##### Added

- support for groups of options and commands in the help using low-level `.helpGroup()` on `Option` and `Command`, and higher-level `.optionsGroup()` and `.commandsGroup()` which can be used in chaining way to specify group title for following options/commands (\[[#&#8203;2328](https://redirect.github.com/tj/commander.js/issues/2328)])
- support for unescaped negative numbers as option-arguments and command-arguments (\[[#&#8203;2339](https://redirect.github.com/tj/commander.js/issues/2339)])
- TypeScript: add `parseArg` property to `Argument` class (\[[#&#8203;2359](https://redirect.github.com/tj/commander.js/issues/2359)])

##### Fixed

- remove bogus leading space in help when option has default value but not a description (\[[#&#8203;2348](https://redirect.github.com/tj/commander.js/issues/2348)])
- `.configureOutput()` now makes copy of settings instead of modifying in-place, fixing side-effects (\[[#&#8203;2350](https://redirect.github.com/tj/commander.js/issues/2350)])

##### Changed

- *Breaking:* Commander 14 requires Node.js v20 or higher
- internal refactor of `Help` class adding `.formatItemList()` and `.groupItems()` methods (\[[#&#8203;2328](https://redirect.github.com/tj/commander.js/issues/2328)])

### [`v13.1.0`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1310-2025-01-21)

[Compare Source](https://redirect.github.com/tj/commander.js/compare/v13.0.0...v13.1.0)

##### Added

- support a pair of long option flags to allow a memorable shortened flag, like `.option('--ws, --workspace')` (\[[#&#8203;2312](https://redirect.github.com/tj/commander.js/issues/2312)])

### [`v13.0.0`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1300-2024-12-30)

[Compare Source](https://redirect.github.com/tj/commander.js/compare/v12.1.0...v13.0.0)

##### Added

- support multiple calls to `.parse()` with default settings (\[[#&#8203;2299](https://redirect.github.com/tj/commander.js/issues/2299)])
- add `.saveStateBeforeParse()` and `.restoreStateBeforeParse()` for use by subclasses (\[[#&#8203;2299](https://redirect.github.com/tj/commander.js/issues/2299)])
- style routines like `styleTitle()` to add color to help using `.configureHelp()` or Help subclass (\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])
- color related support in `.configureOutput()` for `getOutHasColors()`, `getErrHasColors()`, and `stripColor()` (\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])
- Help property for `minWidthToWrap` (\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])
- Help methods for `displayWidth()`, `boxWrap()`, `preformatted()` et al (\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])

##### Changed

- *Breaking*: excess command-arguments cause an error by default, see migration tips (\[[#&#8203;2223](https://redirect.github.com/tj/commander.js/issues/2223)])
- *Breaking*: throw during Option construction for unsupported option flags, like multiple characters after single `-` (\[[#&#8203;2270](https://redirect.github.com/tj/commander.js/issues/2270)])
  - note: support for dual long option flags added in Commander 13.1
- *Breaking*: throw on multiple calls to `.parse()` if `storeOptionsAsProperties: true` (\[[#&#8203;2299](https://redirect.github.com/tj/commander.js/issues/2299)])
- TypeScript: include implicit `this` in parameters for action handler callback (\[[#&#8203;2197](https://redirect.github.com/tj/commander.js/issues/2197)])

##### Deleted

- *Breaking*: `Help.wrap()` refactored into `formatItem()` and `boxWrap()` (\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])

##### Migration Tips

**Excess command-arguments**

It is now an error for the user to specify more command-arguments than are expected. (`allowExcessArguments` is now false by default.)

Old code:

```js
program.option('-p, --port <number>', 'port number');
program.action((options) => {
  console.log(program.args);
});
```

Now shows an error:

```console
$ node example.js a b c
error: too many arguments. Expected 0 arguments but got 3.
```

You can declare the expected arguments. The help will then be more accurate too. Note that declaring
new arguments will change what is passed to the action handler.

```js
program.option('-p, --port <number>', 'port number');
program.argument('[args...]', 'remote command and arguments'); // expecting zero or more arguments
program.action((args, options) => {
  console.log(args);
});
```

Or you could suppress the error, useful for minimising changes in legacy code.

```js
program.option('-p, --port', 'port number');
program.allowExcessArguments();
program.action((options) => {
  console.log(program.args);
});
```

**Stricter option flag parsing**

Commander now throws an error for option flag combinations that are not supported.
In particular, a short flag with multiple characters is now an error.

```js
program.option('-ws, --workspace'); // throws error
```

A short option has a single character:

```js
program.option('-w, --workspace');
```

Or from Commander 13.1 you can have an extra long flag instead of a short flag to allow a more memorable shortcut for the full name:

```js
program.option('--ws, --workspace');
```

### [`v12.1.0`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1210-2024-05-18)

[Compare Source](https://redirect.github.com/tj/commander.js/compare/v12.0.0...v12.1.0)

##### Added

- auto-detect special node flags `node --eval` and `node --print` when call `.parse()` with no arguments (\[[#&#8203;2164](https://redirect.github.com/tj/commander.js/issues/2164)])

##### Changed

- prefix require of Node.js core modules with `node:` (\[[#&#8203;2170](https://redirect.github.com/tj/commander.js/issues/2170)])
- format source files with Prettier (\[[#&#8203;2180](https://redirect.github.com/tj/commander.js/issues/2180)])
- switch from StandardJS to directly calling ESLint for linting (\[[#&#8203;2153](https://redirect.github.com/tj/commander.js/issues/2153)])
- extend security support for previous major version of Commander (\[[#&#8203;2150](https://redirect.github.com/tj/commander.js/issues/2150)])

##### Removed

- removed unimplemented Option.fullDescription from TypeScript definition (\[[#&#8203;2191](https://redirect.github.com/tj/commander.js/issues/2191)])

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these updates again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/). View the [repository job log](https://developer.mend.io/github/X-oss-byte/Nextjs).