Update dependency prettier to v3.7.1 (#5579)
This PR contains the following updates:

| Package | Change | Age | Confidence |
|---|---|---|---|
| [prettier](https://prettier.io) ([source](https://redirect.github.com/prettier/prettier)) | [`3.6.2` -> `3.7.1`](https://renovatebot.com/diffs/npm/prettier/3.2.5/3.7.1) | [![age](https://developer.mend.io/api/mc/badges/age/npm/prettier/3.7.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/prettier/3.2.5/3.7.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>prettier/prettier (prettier)</summary>

### [`v3.7.1`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#371)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.7.0...3.7.1)

[diff](https://redirect.github.com/prettier/prettier/compare/3.7.0...3.7.1)

##### API: Fix performance regression in doc printer ([#&#8203;18342](https://redirect.github.com/prettier/prettier/pull/18342) by [@&#8203;fisker](https://redirect.github.com/fisker))

Prettier 3.7.1 can be very slow when formatting big files, the regression has been fixed.

### [`v3.7.0`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#370)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.6.2...3.7.0)

[diff](https://redirect.github.com/prettier/prettier/compare/3.6.2...3.7.0)

🔗 [Release Notes](https://prettier.io/blog/2025/11/27/3.7.0)

### [`v3.6.2`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#362)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.6.1...3.6.2)

[diff](https://redirect.github.com/prettier/prettier/compare/3.6.1...3.6.2)

##### Markdown: Add missing blank line around code block ([#&#8203;17675](https://redirect.github.com/prettier/prettier/pull/17675) by [@&#8203;fisker](https://redirect.github.com/fisker))



````md
<!-- Input -->
1. Some text, and code block below, with newline after code block

   ```yaml
   ---
   foo: bar
   ```

   1. Another
   2. List

<!-- Prettier 3.6.1 -->
1. Some text, and code block below, with newline after code block

   ```yaml
   ---
   foo: bar
   ```
   1. Another
   2. List

<!-- Prettier 3.6.2 -->
1. Some text, and code block below, with newline after code block

   ```yaml
   ---
   foo: bar
   ```

   1. Another
   2. List
````

### [`v3.6.1`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#361)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.6.0...3.6.1)

[diff](https://redirect.github.com/prettier/prettier/compare/3.6.0...3.6.1)

##### TypeScript: Allow const without initializer ([#&#8203;17650](https://redirect.github.com/prettier/prettier/pull/17650), [#&#8203;17654](https://redirect.github.com/prettier/prettier/pull/17654) by [@&#8203;fisker](https://redirect.github.com/fisker))



```jsx
// Input
export const version: string;

// Prettier 3.6.0 (--parser=babel-ts)
SyntaxError: Unexpected token (1:21)
> 1 | export const version: string;
    |                     ^

// Prettier 3.6.0 (--parser=oxc-ts)
SyntaxError: Missing initializer in const declaration (1:14)
> 1 | export const version: string;
    |              ^^^^^^^^^^^^^^^

// Prettier 3.6.1
export const version: string;
```

##### Miscellaneous: Avoid closing files multiple times ([#&#8203;17665](https://redirect.github.com/prettier/prettier/pull/17665) by [@&#8203;43081j](https://redirect.github.com/43081j))

When reading a file to infer the interpreter from a shebang, we use the
`n-readlines` library to read the first line in order to get the shebang.

This library closes files when it reaches EOF, and we later try close the same
files again. We now close files only if `n-readlines` did not already close
them.

### [`v3.6.0`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#360)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.5.3...3.6.0)

[diff](https://redirect.github.com/prettier/prettier/compare/3.5.3...3.6.0)

🔗 [Release Notes](https://prettier.io/blog/2025/06/23/3.6.0)

### [`v3.5.3`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#353)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.5.2...3.5.3)

[diff](https://redirect.github.com/prettier/prettier/compare/3.5.2...3.5.3)

##### Flow: Fix missing parentheses in `ConditionalTypeAnnotation` ([#&#8203;17196](https://redirect.github.com/prettier/prettier/pull/17196) by [@&#8203;fisker](https://redirect.github.com/fisker))



```jsx
// Input
type T<U> = 'a' | ('b' extends U ? 'c' : empty);
type T<U> = 'a' & ('b' extends U ? 'c' : empty);

// Prettier 3.5.2
type T<U> = "a" | "b" extends U ? "c" : empty;
type T<U> = "a" & "b" extends U ? "c" : empty;

// Prettier 3.5.3
type T<U> = "a" | ("b" extends U ? "c" : empty);
type T<U> = "a" & ("b" extends U ? "c" : empty);
```

### [`v3.5.2`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#352)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.5.1...3.5.2)

[diff](https://redirect.github.com/prettier/prettier/compare/3.5.1...3.5.2)

##### Remove `module-sync` condition ([#&#8203;17156](https://redirect.github.com/prettier/prettier/pull/17156) by [@&#8203;fisker](https://redirect.github.com/fisker))

In Prettier 3.5.0, [we added `module-sync` condition to `package.json`](https://prettier.io/blog/2025/02/09/3.5.0#use-esm-entrypoint-for-requireesm-16958-by-tats-u), so that `require("prettier")` can use ESM version, but turns out it doesn't work if CommonJS and ESM plugins both imports builtin plugins. To solve this problem, we decide simply remove the `module-sync` condition, so `require("prettier")` will still use the CommonJS version, we'll revisit until `require(ESM)` feature is more stable.

### [`v3.5.1`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#351)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.5.0...3.5.1)

[diff](https://redirect.github.com/prettier/prettier/compare/3.5.0...3.5.1)

##### Fix CLI crash when cache for old version exists ([#&#8203;17100](https://redirect.github.com/prettier/prettier/pull/17100) by [@&#8203;sosukesuzuki](https://redirect.github.com/sosukesuzuki))

Prettier 3.5 uses a different cache format than previous versions, Prettier 3.5.0 crashes when reading existing cache file, Prettier 3.5.1 fixed the problem.

##### Support dockercompose and github-actions-workflow in VSCode ([#&#8203;17101](https://redirect.github.com/prettier/prettier/pull/17101) by [@&#8203;remcohaszing](https://redirect.github.com/remcohaszing))

Prettier now supports the `dockercompose` and `github-actions-workflow` languages in Visual Studio Code.

### [`v3.5.0`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#350)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.4.2...3.5.0)

[diff](https://redirect.github.com/prettier/prettier/compare/3.4.2...3.5.0)

🔗 [Release Notes](https://prettier.io/blog/2025/02/09/3.5.0.html)

### [`v3.4.2`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#342)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.4.1...3.4.2)

[diff](https://redirect.github.com/prettier/prettier/compare/3.4.1...3.4.2)

##### Treat U+30A0 & U+30FB in Katakana Block as CJK ([#&#8203;16796](https://redirect.github.com/prettier/prettier/pull/16796) by [@&#8203;tats-u](https://redirect.github.com/tats-u))

Prettier doesn't treat U+30A0 & U+30FB as Japanese. U+30FB is commonly used in Japanese to represent the delimitation of first and last names of non-Japanese people or “and”. The following “C言語・C++・Go・Rust” means “C language & C++ & Go & Rust” in Japanese.



```md
<!-- Input (--prose-wrap=never) -->

C言
語
・
C++
・
Go
・
Rust

<!-- Prettier 3.4.1 -->
C言語・ C++ ・ Go ・ Rust

<!-- Prettier 3.4.2 -->
C言語・C++・Go・Rust
```

U+30A0 can be used as the replacement of the `-` in non-Japanese names (e.g. “Saint-Saëns” (Charles Camille Saint-Saëns) can be represented as “サン゠サーンス” in Japanese), but substituted by ASCII hyphen (U+002D) or U+FF1D (full width hyphen) in many cases (e.g. “サン=サーンス” or “サン＝サーンス”).

##### Fix comments print on class methods with decorators ([#&#8203;16891](https://redirect.github.com/prettier/prettier/pull/16891) by [@&#8203;fisker](https://redirect.github.com/fisker))



```jsx
// Input
class A {
  @&#8203;decorator
  /** 
   * The method description
   *
  */
  async method(foo: Foo, bar: Bar) {
    console.log(foo);
  }
}

// Prettier 3.4.1
class A {
  @&#8203;decorator
  async /**
   * The method description
   *
   */
  method(foo: Foo, bar: Bar) {
    console.log(foo);
  }
}

// Prettier 3.4.2
class A {
  @&#8203;decorator
  /**
   * The method description
   *
   */
  async method(foo: Foo, bar: Bar) {
    console.log(foo);
  }
}
```

##### Fix non-idempotent formatting ([#&#8203;16899](https://redirect.github.com/prettier/prettier/pull/16899) by [@&#8203;seiyab](https://redirect.github.com/seiyab))

This bug fix is not language-specific. You may see similar change in any languages. This fixes regression in 3.4.0 so change caused by it should yield same formatting as 3.3.3.



```jsx
// Input
<div>
  foo
  <span>longlonglonglonglonglonglonglonglonglonglonglonglonglonglongl foo</span>
  , abc
</div>;

// Prettier 3.4.1 (first)
<div>
  foo
  <span>
    longlonglonglonglonglonglonglonglonglonglonglonglonglonglongl foo
  </span>, abc
</div>;

// Prettier 3.4.1 (second)
<div>
  foo
  <span>longlonglonglonglonglonglonglonglonglonglonglonglonglonglongl foo</span>
  , abc
</div>;

// Prettier 3.4.2
<div>
  foo
  <span>longlonglonglonglonglonglonglonglonglonglonglonglonglonglongl foo</span>
  , abc
</div>;
```

### [`v3.4.1`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#341)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.4.0...3.4.1)

[diff](https://redirect.github.com/prettier/prettier/compare/3.4.0...3.4.1)

##### Remove unnecessary parentheses around assignment in `v-on` ([#&#8203;16887](https://redirect.github.com/prettier/prettier/pull/16887) by [@&#8203;fisker](https://redirect.github.com/fisker))



```vue
<!-- Input -->
<template>
  <button @&#8203;click="foo += 2">Click</button>
</template>

<!-- Prettier 3.4.0 -->
<template>
  <button @&#8203;click="(foo += 2)">Click</button>
</template>

<!-- Prettier 3.4.1 -->
<template>
  <button @&#8203;click="foo += 2">Click</button>
</template>
```

### [`v3.4.0`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#340)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.3.3...3.4.0)

[diff](https://redirect.github.com/prettier/prettier/compare/3.3.3...3.4.0)

🔗 [Release Notes](https://prettier.io/blog/2024/11/26/3.4.0.html)

### [`v3.3.3`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#333)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.3.2...3.3.3)

[diff](https://redirect.github.com/prettier/prettier/compare/3.3.2...3.3.3)

##### Add parentheses for nullish coalescing in ternary ([#&#8203;16391](https://redirect.github.com/prettier/prettier/pull/16391) by [@&#8203;cdignam-segment](https://redirect.github.com/cdignam-segment))

This change adds clarity to operator precedence.



```js
// Input
foo ? bar ?? foo : baz;
foo ?? bar ? a : b;
a ? b : foo ?? bar;

// Prettier 3.3.2
foo ? bar ?? foo : baz;
foo ?? bar ? a : b;
a ? b : foo ?? bar;

// Prettier 3.3.3
foo ? (bar ?? foo) : baz;
(foo ?? bar) ? a : b;
a ? b : (foo ?? bar);
```

##### Add parentheses for decorator expressions ([#&#8203;16458](https://redirect.github.com/prettier/prettier/pull/16458) by [@&#8203;y-schneider](https://redirect.github.com/y-schneider))

Prevent parentheses around member expressions or tagged template literals from being removed to follow the stricter parsing rules of TypeScript 5.5.



```ts
// Input
@&#8203;(foo`tagged template`)
class X {}

// Prettier 3.3.2
@&#8203;foo`tagged template`
class X {}

// Prettier 3.3.3
@&#8203;(foo`tagged template`)
class X {}
```

##### Support `@let` declaration syntax ([#&#8203;16474](https://redirect.github.com/prettier/prettier/pull/16474) by [@&#8203;sosukesuzuki](https://redirect.github.com/sosukesuzuki))

Adds support for Angular v18 `@let` declaration syntax.

Please see the following code example. The `@let` declaration allows you to define local variables within the template:



```html
@&#8203;let name = 'Frodo';

<h1>Dashboard for {{name}}</h1>
Hello, {{name}}
```

For more details, please refer to the excellent blog post by the Angular Team: [Introducing @&#8203;let in Angular](https://blog.angular.dev/introducing-let-in-angular-686f9f383f0f).

We also appreciate the Angular Team for kindly answering our questions to implement this feature.

### [`v3.3.2`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#332)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.3.1...3.3.2)

[diff](https://redirect.github.com/prettier/prettier/compare/3.3.1...3.3.2)

##### Fix handlebars path expressions starts with `@` ([#&#8203;16358](https://redirect.github.com/prettier/prettier/pull/16358) by [@&#8203;Princeyadav05](https://redirect.github.com/Princeyadav05))



```hbs
{{! Input }}
<div>{{@&#8203;x.y.z}}</div>

{{! Prettier 3.3.1 }}
<div>{{@&#8203;x}}</div>

{{! Prettier 3.3.2 }}
<div>{{@&#8203;x.y.z}}</div>
```

### [`v3.3.1`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#331)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.3.0...3.3.1)

[diff](https://redirect.github.com/prettier/prettier/compare/3.3.0...3.3.1)

##### Preserve empty lines in front matter ([#&#8203;16347](https://redirect.github.com/prettier/prettier/pull/16347) by [@&#8203;fisker](https://redirect.github.com/fisker))



```markdown
<!-- Input -->
---
foo:
  - bar1

  - bar2

  - bar3
---
Markdown

<!-- Prettier 3.3.0 -->

---
foo:
  - bar1
  - bar2
  - bar3
---

Markdown

<!-- Prettier 3.3.1 -->
---
foo:
  - bar1

  - bar2

  - bar3
---

Markdown
```

##### Preserve explicit language in front matter ([#&#8203;16348](https://redirect.github.com/prettier/prettier/pull/16348) by [@&#8203;fisker](https://redirect.github.com/fisker))



```markdown
<!-- Input -->
---yaml
title: Hello
slug: home
---

<!-- Prettier 3.3.0 -->
---
title: Hello
slug: home
---

<!-- Prettier 3.3.1 -->
---yaml
title: Hello
slug: home
---
```

##### Avoid line breaks in import attributes ([#&#8203;16349](https://redirect.github.com/prettier/prettier/pull/16349) by [@&#8203;fisker](https://redirect.github.com/fisker))



```jsx
// Input
import something from "./some-very-very-very-very-very-very-very-very-long-path.json" with { type: "json" };

// Prettier 3.3.0
import something from "./some-very-very-very-very-very-very-very-very-long-path.json" with { type:
  "json" };

// Prettier 3.3.1
import something from "./some-very-very-very-very-very-very-very-very-long-path.json" with { type: "json" };
```

### [`v3.3.0`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#330)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.2.5...3.3.0)

[diff](https://redirect.github.com/prettier/prettier/compare/3.2.5...3.3.0)

🔗 [Release Notes](https://prettier.io/blog/2024/06/01/3.3.0.html)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/). View the [repository job log](https://developer.mend.io/github/X-oss-byte/Nextjs).